name: Release
on:
  push:
    tags:
      - '*'  # Trigger on version tags

env:
  UV_VERSION: "0.4.27"

jobs:
  build-and-release:
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    runs-on: ubuntu-24.04
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/${{ env.UV_VERSION }}/install.sh | sh

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install dependencies
        run: uv sync

      - name: Install package
        run: uv pip install -e .

      - name: Build package
        run: uv build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Minimize uv cache
        run: uv cache prune --ci
